# Sesi 4 
Numpy

In [6]:
import numpy as np

In [8]:
firstArray = np.array([1,2,3,4])

In [9]:
firstArray

array([1, 2, 3, 4])

In [10]:
np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

In [11]:
np.ones(6)

array([1., 1., 1., 1., 1., 1.])

In [13]:
np.empty(6)
#random nyetak elemen terakhir yg disimpan, yaitu diatas ini adalah 1

array([1., 1., 1., 1., 1., 1.])

In [15]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [20]:
np.arange(2,6,8)

array([2])

In [21]:
np.arange(1,11)


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

# Add, Delete,Sort 

In [22]:
arr = np.array([1,2,3,4,5,6,7,8])

In [23]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8])

In [24]:
np.append(arr,[1,3,5])

array([1, 2, 3, 4, 5, 6, 7, 8, 1, 3, 5])

In [25]:
np.append([11,12],arr)

array([11, 12,  1,  2,  3,  4,  5,  6,  7,  8])

In [26]:
np.delete(arr,[1])

array([1, 3, 4, 5, 6, 7, 8])

In [27]:
np.sort(arr)

array([1, 2, 3, 4, 5, 6, 7, 8])

# # Shape & Size

In [31]:
array_example = np.array([[[0,1,2,3],
                         [4,5,6,7]],
                        
                        [[0,1,2,3],
                        [4,5,6,7]],
                        
                        [[0,1,2,3],
                        [4,5,6,7]]])

In [32]:
print(array_example)

[[[0 1 2 3]
  [4 5 6 7]]

 [[0 1 2 3]
  [4 5 6 7]]

 [[0 1 2 3]
  [4 5 6 7]]]


In [33]:
array_example.ndim
#untuk ngecek berapa dimensinya yang ada di array

3

In [35]:
array_example.size

24

In [36]:
array_example.shape
#untuk ngecek jumlah tuple integer : dimensi, lebar, panjang

(3, 2, 4)

In [38]:
arr_one = np.array([[1,2,3,4,5]])

In [39]:
arr_one.ndim

2

In [40]:
arr_one.size

5

In [41]:
arr_one.shape

(1, 5)

# #Reshape

In [42]:
a = np.arange(6)
print(a)

[0 1 2 3 4 5]


In [43]:
a.reshape(2,3)

array([[0, 1, 2],
       [3, 4, 5]])

In [44]:
a.reshape(3,2)

array([[0, 1],
       [2, 3],
       [4, 5]])

In [45]:
a.reshape(1,6)

array([[0, 1, 2, 3, 4, 5]])

In [46]:
a.reshape(6,1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

In [47]:
a.reshape(1,6)

array([[0, 1, 2, 3, 4, 5]])

# Convert 1D to 2D 

In [48]:
a

array([0, 1, 2, 3, 4, 5])

In [49]:
a.shape

(6,)

In [51]:
a2 = a[np.newaxis]
#seperti menambahkan 1 axis sumbu X baru ke dalam a, disimpan ke dalam a2

In [52]:
a2

array([[0, 1, 2, 3, 4, 5]])

In [53]:
a2.shape

(1, 6)

In [54]:
a3 = a[np.newaxis,:]

In [55]:
a3

array([[0, 1, 2, 3, 4, 5]])

In [56]:
a3.shape

(1, 6)

In [58]:
b2 = np.expand_dims(a,axis=1)

In [60]:
b2.shape

(6, 1)

In [61]:
b3 = np.expand_dims(a,axis=0)

In [62]:
b3.shape

(1, 6)

In [63]:
b2.ndim

2

In [64]:
b2.size

6

In [65]:
b3.ndim

2

In [66]:
b3.size

6

# #Indexing & Slicing

In [67]:
a

array([0, 1, 2, 3, 4, 5])

In [71]:
print(a)
print(a[0])
print(a[2])

[0 1 2 3 4 5]
0
2


In [73]:
a[0:2]

array([0, 1])

In [74]:
a[:4]

array([0, 1, 2, 3])

In [75]:
a[-1]

5

In [81]:
a[2:]

array([2, 3, 4, 5])

# #Create Array from Existing Data

In [78]:
arr4 = np.arange(1,11)

In [79]:
arr4

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [82]:
arr5 = arr[3:8]

In [83]:
arr5

array([4, 5, 6, 7, 8])

In [84]:
a_1 = np.array([[1,1],[2,2]])

In [85]:
a_2 = np.array([[3,3],[4,4]])

In [86]:
print(a_1)
print(a_2)

[[1 1]
 [2 2]]
[[3 3]
 [4 4]]


In [89]:
np.vstack((a_1,a_2))

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [90]:
np.hstack((a_1,a_2))

array([[1, 1, 3, 3],
       [2, 2, 4, 4]])

# #Array Operations

In [91]:
a

array([0, 1, 2, 3, 4, 5])

In [92]:
a.sum()

15

In [98]:
b = np.array([[1,3],[2,1]])

In [99]:
b

array([[1, 3],
       [2, 1]])

In [95]:
b.sum()

6

In [100]:
b.sum(axis=0)

array([3, 4])

In [101]:
b.sum(axis=1)

array([4, 3])

In [103]:
data = np.array([1,2])

In [104]:
data

array([1, 2])

In [105]:
data * 2

array([2, 4])

In [106]:
data = np.array([[1,2,3,4,5,6],[7,8,9,10,11,12],[13,14,15,16,17,18]])

In [107]:
data.sum()

171

In [114]:
data.sum(axis=0)

array([21, 24, 27, 30, 33, 36])

In [109]:
data.sum(axis=1)

array([21, 57, 93])

In [110]:
data.max()

18

In [111]:
data.min()

1

In [112]:
data.min(axis=0)

array([1, 2, 3, 4, 5, 6])

# #Matrices

In [116]:
np.array([[1,2],[3,4]])

array([[1, 2],
       [3, 4]])

In [117]:
np.ones([3,2])

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [118]:
np.zeros([3,2])

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [119]:
np.random.random([4,5])

array([[0.91183629, 0.84743208, 0.13349794, 0.09384283, 0.26220263],
       [0.97465333, 0.09020052, 0.69843413, 0.17050607, 0.30927128],
       [0.51324689, 0.90585374, 0.09134027, 0.6220346 , 0.32304177],
       [0.3819538 , 0.47530136, 0.04486585, 0.56620873, 0.82034214]])

In [120]:
data = np.array([[1,2],[3,4]])

In [125]:
data

array([[1, 2],
       [3, 4]])

In [122]:
ones = np.ones([2,2])

In [123]:
ones

array([[1., 1.],
       [1., 1.]])

In [126]:
data + ones

array([[2., 3.],
       [4., 5.]])

# #Indexing & Slicing

In [127]:
data = np.array([[1,2],[3,4],[5,6]])

In [128]:
data

array([[1, 2],
       [3, 4],
       [5, 6]])

In [129]:
data[0]

array([1, 2])

In [130]:
data[1]

array([3, 4])

In [131]:
data[0,1]

2

In [132]:
data[0:2,0]

array([1, 3])

In [133]:
data[:,0]

array([1, 3, 5])

In [134]:
print(data.T)

[[1 3 5]
 [2 4 6]]
